usage:	java org.teherba.churchcal.MainCalendar [language [variant [-s] [year [format]]]]
      	language = deu, eng, fra ...
      	variant = ev, rk, tr ...
      	-s : Sundays and Holidays only
      	year 1583..4099
      	format = html, java, sql, table, xml ...
