<%--
    Display a calendar generated by a subclass of BaseCalendar
    @(#) $Id: show.jsp 882 2012-02-12 21:09:04Z gfis $
	2008-04-04: use constructor(2)
    2007-02-13: package org.teherba.churchcal
    2005-12-08, Georg Fischer
--%>
<%--
 * Copyright 2006 Dr. Georg Fischer <punctum at punctum dot kom>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
--%>
<%@page import="org.teherba.churchcal.EasterCalendar"%>
<%@page import="org.teherba.churchcal.DeuChurchCalendar"%>
<%
    String CVSID = "@(#) $Id: show.jsp 882 2012-02-12 21:09:04Z gfis $";
    Object 
    field = session.getAttribute("calendar");
    EasterCalendar calendar = (field != null) 
    		? (EasterCalendar) field 
    		: new DeuChurchCalendar(0, DeuChurchCalendar.EVANGELIC);
    calendar.printHTML(out, 6); 
%>
